blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(300)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingDetailView, MailingCreateView, MailingDeleteView,\
    mailing_report, MailingLogListView, toggle_mailing_status, MailingUpdateView

app_name = MailingConfig.name


urlpatterns = [
    path('', MailingListView.as_view(), name='list'),
    path('view/<int:pk>/', MailingDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MailingUpdateView.as_view(), name='edit_mailing'),
    path('create/', MailingCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),
    path('report/', mailing_report, name='report'),
    path('<int:pk>/logs/', MailingLogListView.as_view(), name='mailing_logs'),
    path('toggle/<int:pk>/<str:action>/', toggle_mailing_status, name='toggle_mailing_status')
    ]

mailing/models.py
from django.db import models
from clients.models import Client
from users.models import User


class Message(models.Model):
    """Модель для хранения информации о сообщениях для рассылки"""

    subject = models.CharField(max_length=255, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        db_table = 'messages'


class Mailing(models.Model):
    """Модель для хранения информации о рассылках"""

    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц')
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена')
    )

    send_time = models.TimeField(verbose_name='Время старта рассылки')
    end_time = models.DateTimeField(verbose_name='Время окончания рассылки', null=True, blank=True)
    frequency = models.CharField(max_length=20, choices=PERIODS, verbose_name='Периодичность')
    status = models.CharField(max_length=20, choices=STATUSES,
                              verbose_name='Статус рассылки', default='STATUS_CREATED')

    # Связь с клиентами (ManyToMany)
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')

    # Связь с сообщением (ForeignKey)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')

    # Связь с пользователем
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', default=None)

    def __str__(self):
        return f'Рассылка от {self.send_time}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        db_table = 'mailings'


class MailingLog(models.Model):
    """Модель для хранения логов рассылок"""

    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка')

    )

    last_try = models.DateTimeField(verbose_name='Дата и время последней попытки', auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='Статус попытки')
    response = models.TextField(verbose_name='Ответ почтового сервера', null=True, blank=True)

    # Связь с рассылкой (ForeignKey)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'Рассылка от {self.last_try}. Статус: {self.status}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылок'
        db_table = 'mailing_logs'

mailing/forms.py
from django import forms
from mailing.models import Mailing, Message
from clients.models import Client


class FormStyleMixin:
    """Класс для стилизации форм"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования рассылок"""

    def __init__(self, *args, **kwargs):
        """Извлекает аргумент user из kwargs, который был передан в контроллере
        И в поле 'clients' формирует список из клиентов, принадлежащих этому пользователю"""
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['clients'].queryset = Client.objects.filter(user=user)

    send_time = forms.TimeField(
        label='Время рассылки',
        widget=forms.TimeInput(attrs={'type': 'time'}),
    )

    class Meta:
        model = Mailing
        fields = ('send_time', 'frequency', 'clients')


class MessageForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования сообщения"""
    class Meta:
        model = Message
        fields = ('subject', 'body')

mailing/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from mailing.forms import MailingForm, MessageForm
from mailing.models import Mailing, MailingLog, Message


class UserMailingsMixin:
    """Миксин для фильтрации рассылок по пользователю.
    Если пользователь менеджер - возвращаем все рассылки.
    Если обычный пользователь - то только его рассылки"""
    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return Mailing.objects.all()
        return Mailing.objects.filter(user=user)


class MailingListView(LoginRequiredMixin, UserPassesTestMixin, UserMailingsMixin, ListView):
    """Список рассылок для просмотра"""
    model = Mailing

    def test_func(self):
        """Открывает доступ менеджеру к списку рассылок"""
        return True


class MailingDetailView(UserMailingsMixin, DetailView):
    """Подробная информация о рассылке"""
    model = Mailing

    def get_context_data(self, **kwargs):
        """Добавляет информацию о логах рассылки в контекст"""
        context_data = super().get_context_data(**kwargs)
        context_data['mailing_logs'] = MailingLog.objects.filter(mailing=self.object)
        return context_data


class MailingCreateView(UserPassesTestMixin, UserMailingsMixin, CreateView):
    """Создание новой рассылки"""
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:list')

    def test_func(self):
        """Запрещает менеджеру создавать рассылки"""
        return not self.request.user.is_staff

    def get_form_kwargs(self):
        """Добавляет аргумент user в конструктор формы, равный текущему пользователю"""
        kwargs = super().get_form_kwargs()
        user = self.request.user
        # Фильтруем клиентов, принадлежащих текущему пользователю
        kwargs['user'] = user
        return kwargs

    def get_context_data(self, **kwargs):
        """Добавляет форму для создания сообщения в контекст"""
        context = super().get_context_data(**kwargs)
        context['message_form'] = MessageForm()
        return context

    def form_valid(self, form):
        """Обрабатывает форму создания рассылки и сообщения"""

        # Обработка формы сообщения
        message_form = MessageForm(self.request.POST)
        if message_form.is_valid():
            message = message_form.save()

            # Получаем пользователя
            user = self.request.user
            form.instance.user = user

            # Сохраняем рассылку
            mailing = form.save(commit=False)
            mailing.message = message
            mailing.save()

            # Получаем клиентов для рассылки
            selected_clients = form.cleaned_data['clients']
            mailing.clients.set(selected_clients)
            mailing.save()

            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class MailingUpdateView(UserPassesTestMixin, UpdateView):
    """Редактирование существующей рассылки"""
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'

    def test_func(self):
        """Запрещает менеджеру редактировать рассылки"""
        return not self.request.user.is_staff

    def get_success_url(self):
        """Получаем урл после успешного редактирования"""
        return reverse('mailing:view', args=[self.kwargs['pk']])

    def get_form_kwargs(self):
        """Добавляет аргумент user в конструктор формы, равный текущему пользователю"""
        kwargs = super().get_form_kwargs()
        user = self.request.user
        kwargs['user'] = user
        return kwargs

    def get_context_data(self, **kwargs):
        """Добавляет форму сообщения в контекст"""
        context = super().get_context_data(**kwargs)
        context['message_form'] = MessageForm(instance=self.object.message)
        return context

    def form_valid(self, form):
        message_form = MessageForm(self.request.POST, instance=self.object.message)
        if message_form.is_valid():
            message = message_form.save()

            form.instance.user = self.request.user
            form.instance.message = message
            form.save()

            selected_clients = form.cleaned_data['clients']
            form.instance.clients.set(selected_clients)
            form.save()

            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class MailingDeleteView(UserPassesTestMixin, DeleteView):
    """Удаляет рассылку"""
    model = Mailing
    success_url = reverse_lazy('mailing:list')

    def test_func(self):
        """Запрещает менеджеру удалять рассылки"""
        return not self.request.user.is_staff


def toggle_mailing_status(request, pk, action):
    """Активирует / отключает рассылку"""

    mailing = get_object_or_404(Mailing, pk=pk)

    if action == 'start':
        # Запуск рассылки
        mailing.status = Mailing.STATUS_STARTED
        mailing.save()
    elif action == 'stop':
        # Остановка рассылки
        mailing.status = Mailing.STATUS_DONE
        mailing.save()

    return HttpResponseRedirect(reverse('mailing:view', args=[pk]))


def mailing_report(request):
    """Отчет о рассылках"""

    user = request.user
    mailings = Mailing.objects.filter(user=user)
    context = {
        'mailings': mailings,
    }
    return render(request, 'mailing/mailing_report.html', context)


class MailingLogListView(ListView):
    """Просмотр логов рассылки"""

    model = MailingLog
    template_name = 'mailing/mailing_logs_list.html'
    context_object_name = 'mailing_logs'

    def get_queryset(self):
        """Фильтруем логи по рассылке"""
        queryset = super().get_queryset()
        queryset = queryset.filter(mailing_id=self.kwargs['pk'])
        return queryset

    def get_context_data(self, **kwargs):
        """Добавляем pk рассылки в контекст"""
        context = super().get_context_data(**kwargs)
        context['mailing_pk'] = self.kwargs['pk']
        return context

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'main/base.html' %}

{% block title %}Подтверждение удаления рассылки{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mt-4">Подтверждение удаления рассылки</h1>
            <hr>
            <br>
            <p>Вы уверены, что хотите удалить рассылку сообщения "{{ object.message.subject }}"?</p>
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Удалить</button>
                <a href="{% url 'mailing:list' %}" class="btn btn-outline-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'main/base.html' %}

{% block title %}Информация о рассылке - Mail Flow{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 mt-5">Детали рассылки</h1>
            <br>
            <br>
            <br>
            <dl class="row">
                <dt class="col-sm-3">Время отправки:</dt>
                <dd class="col-sm-9">{{ object.send_time }}</dd>

                <dt class="col-sm-3">Периодичность:</dt>
                <dd class="col-sm-9">{{ object.get_frequency_display }}</dd>

                <dt class="col-sm-3">Сообщение:</dt>
                <dd class="col-sm-9">{{ object.message.body }}</dd>

                <dt class="col-sm-3">Статус:</dt>
                <dd class="col-sm-9">
                    {% if object.status == 'started' %}
                    <span class="text-success">Рассылка активирована</span>
                    {% elif object.status == 'done' %}
                    <span class="text-danger">Рассылка остановлена</span>
                    {% else %}
                    <span class="text-muted">Рассылка не активирована</span>
                    {% endif %}


                </dd>

                <dt class="col-sm-3">Клиенты:</dt>
                <dd class="col-sm-9">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col" class="light-text">Имя</th>
                            <th scope="col" class="light-text">Email</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for client in object.clients.all %}
                        <tr>
                            <td class="light-text"> {{ client.full_name }}</td>
                            <td class="light-text">{{ client.email }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </dd>
            </dl>


            <div class="mt-4">
                {% if object.status == 'created' %}
                <a href="{% url 'mailing:toggle_mailing_status' pk=object.pk action='start' %}"
                   class="btn btn-outline-success">Запустить
                    рассылку</a>
                {% elif object.status == 'done' %}
                <a href="{% url 'mailing:toggle_mailing_status' pk=object.pk action='start' %}" class="btn btn-outline-success">Запустить
                    рассылку</a>
                {% elif object.status == 'started' %}
                <a href="{% url 'mailing:toggle_mailing_status' pk=object.pk action='stop' %}" class="btn btn-outline-danger">Остановить
                    рассылку</a>
                {% endif %}
            </div>
            <br>
            <br>
            {% if not user.is_staff %}
            <nav class="nav nav-masthead justify-content-center">

                <a class="nav-link" href="{% url 'mailing:mailing_logs' pk=object.pk %}">Просмотр Логов</a>


                <a class="nav-link" href="{% url 'mailing:edit_mailing' pk=object.pk %}">Редактировать</a>

                <a class="nav-link" href="{% url 'mailing:delete' pk=object.pk %}">Удалить</a>
            </nav>
            {% endif %}
        </div>
    </div>
    {% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'main/base.html' %}

{% block title %}Создать рассылку{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card bg-dark text-white">
                <div class="card-header">
                    <h2>{% if object %} Редактирование рассылки {% else %} Создание рассылки {% endif %}</h2>
                </div>

                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_table }}
                        {{ message_form.as_table }}
                        <button type="submit" class="btn btn-outline-primary mt-3">Сохранить</button>
                        <a href="{% url 'mailing:list' %}" class="btn btn-outline-secondary mt-3">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'main/base.html' %}

{% block title %}Рассылки - Mail Flow{% endblock %}

{% block content %}
<div class="col-12 md-5">
    <h1 class="mt-5">Список рассылок</h1>
    <br>
    <br>

    <table class="table table-striped">
        <thead>
        <tr>
            <th class="text-white">Сообщение</th>
            {% if user.is_staff %}
            <th class="text-white">Пользователь</th>
            {% endif %}
            <th class="text-white">Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td class="text-white">
                <nav class="nav nav-masthead justify-content-center">
                    <a href="{% url 'mailing:view' pk=object.pk %}" class="nav-link">{{ object.message.subject }}</a>
                </nav>
            </td>
            {% if user.is_staff %}

            <td class="text-white">
                <nav class="nav nav-masthead justify-content-center">
                    <a href="{% url 'users:view' pk=object.user.pk %}" class="nav-link">{{ object.user.email }}</a>
                </nav>
            </td>
            {% endif %}
            <td class="text-white">
                {% if object.status == 'done' %}
                Завершена
                {% elif object.status == 'started' %}
                Запущена
                {% elif object.status == 'created' %}
                Создана
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <br>
    <br>
</div>
{% if not user.is_staff %}
<nav class="nav nav-masthead justify-content-center">
    <a href="{% url 'mailing:create' %}" class="nav-link">Добавить рассылку</a>
    <a href="{% url 'mailing:report' %}" class="nav-link">Отчет о рассылках</a>
</nav>
{% endif %}
{% endblock %}

mailing/templates/mailing/mailing_logs_list.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Логи рассылки</h1>
<hr>
<br>
{% if mailing_logs %}
<table class="table">
    <thead>
    <tr>
        <th scope="col" class="light-text">Последняя отправка</th>
        <th scope="col" class="light-text">Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for log in mailing_logs %}
    <tr>
        <td class="light-text">{{ log.last_try }}</td>
        <td class="light-text">{{ log.status }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p class="light-text">Нет логов для отображения.</p>
{% endif %}
<nav class="nav nav-masthead justify-content-center">
    <div class="mt-4">
         <a class="nav-link" href="{% url 'mailing:view' pk=mailing_pk %}" >Назад к рассылке</a>
    </div>
</nav>
{% endblock %}

mailing/templates/mailing/mailing_report.html
{% extends 'main/base.html' %}

{% block title %}Отчет о рассылках{% endblock %}

{% block content %}
<div class="container">
    <h2>Отчет о рассылках</h2>
    <br>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th class="light-text">Тема письма</th>
                <th class="light-text">Статус рассылки</th>
                <th class="light-text">Количество клиентов</th>
                <th class="light-text">Время рассылки</th>
            </tr>
        </thead>
        <tbody>
            {% for mailing in mailings %}
            <tr>
                <td class="light-text">{{ mailing.message.subject }}</td>
                <td class="light-text">{{ mailing.get_status_display }}</td>
                <td class="light-text">{{ mailing.clients.count }}</td>
                <td class="light-text">{{ mailing.send_time }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Сообщение</h2>
<p><strong>Тема письма:</strong> {{ message.subject }}</p>
<p><strong>Тело письма:</strong></p>
<p>{{ message.body }}</p>
{% endblock %}