blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(300)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView, verify_email, UserListView, UserDetailView, toggle_activity
from users.apps import UsersConfig

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView .as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView .as_view(), name='profile'),
    path('verify_email/<str:key>/', verify_email, name='verify_email'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('view/<int:pk>/', UserDetailView.as_view(), name='view'),
    path('toggle_activity/<int:pk>/', toggle_activity, name='toggle_activity'),

    ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    """Модель пользователя"""

    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)

    phone = models.CharField(max_length=30, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)

    # Верификация
    verify_key = models.CharField(max_length=255, **NULLABLE, verbose_name='Ключ верификации')
    is_verified = models.BooleanField(default=False, verbose_name='Верифицирован')

    # Переопределяем поле для аутентификации
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        db_table = 'users'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class FormStyleMixin:
    """Миксин для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['placeholder'] = f'{field.label}'
            field.label = ''
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    """Форма для регистрации клиента"""

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


class UserProfileForm(FormStyleMixin, UserChangeForm):
    """Форма для редактирования профиля клиента"""

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from mailing.models import Mailing
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from users.services import send_email_for_verify, send_block_email


# Create your views here.
class RegisterView(CreateView):
    """регистрация пользователя"""

    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            verify_key = secrets.token_urlsafe(32)

            user = form.save(commit=False)
            user.verify_key = verify_key
            user.save()

            current_site = get_current_site(self.request)
            verify_link = f"http://{current_site.domain}{reverse('users:verify_email', args=[verify_key])}"
            send_email_for_verify(user, verify_link)
            return render(self.request, 'users/verification/verify_email.html')

        return super().form_valid(form)


class ProfileView(UpdateView):
    """Отображение профиля пользователя"""

    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('main:home')

    def get_object(self, queryset=None):
        return self.request.user


def verify_email(request, key):
    """Верификация по почте"""

    user = User.objects.filter(verify_key=key).first()

    if user:
        user.is_verified = True
        user.save()
        return render(request, 'users/verification/verify_success.html')
    else:
        return render(request, 'users/verification/verify_error.html')


class UserListView(UserPassesTestMixin, ListView):
    """Просмотр списка пользователей"""
    model = User

    def test_func(self):
        return self.request.user.is_staff


class UserDetailView(DetailView):
    """Просмотр информации о пользователе"""
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.object
        mailings_count = len(Mailing.objects.filter(user=user))
        active_mailings_count = len(Mailing.objects.filter(user=user, status='started'))
        context['mailings_count'] = mailings_count
        context['active_mailings_count'] = active_mailings_count
        return context


@user_passes_test(lambda u: u.is_staff)
def toggle_activity(request, pk):
    """Активирует / деактивирует пользователя"""

    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
        send_block_email(user_item)
    else:
        user_item.is_active = True

    user_item.save()

    return redirect(reverse('users:view', kwargs={'pk': pk}))

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block title %}Вход в систему - Mail Flow{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="mt-5 mb-4">Вход в систему</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-secondary">Войти</button>
            </form>
            <br>
            <p class="mt-3">Еще не зарегистрированы?</p>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'users:register' %}">Зарегистрируйтесь</a>
            </nav>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card bg-dark text-white">
        <div class="card-header">
          Регистрация
        </div>
        <div class="card-body">
          <form method="POST" class="form bg-dark text-white">
            {% csrf_token %}

            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-secondary">Зарегистрироваться</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'main/base.html' %}

{% block title %}Клиент - Mail Flow{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 mt-5">Подробнее о пользователе</h1>
            <hr>
            <br>

            <div class="row">
                <div class="col-12">
                    <dl class="row">
                        <dt class="col-sm-3">ФИО:</dt>
                        <dd class="col-sm-9">{% if object.full_name %}{{ object.full_name }}{% else %}Не указано{% endif%}
                        </dd>

                        <dt class="col-sm-3">Email:</dt>
                        <dd class="col-sm-9">{{ object.email }}</dd>

                        <dt class="col-sm-3">Телефон:</dt>
                        <dd class="col-sm-9">{% if object.phone %}{{ object.phone }}{% else %}Не указан{% endif %}</dd>

                        <dt class="col-sm-3">Всего рассылок:</dt>
                        <dd class="col-sm-9">{{ mailings_count }}</dd>

                        <dt class="col-sm-3">Запущенных рассылок:</dt>
                        <dd class="col-sm-9" style="white-space: nowrap;">{{ active_mailings_count }}</dd>


                    </dl>
                </div>
            </div>
            <hr>

            <br>

            <div class="light-text">
                {% if object.is_active %}
                <a class="btn btn-outline-danger"
                   href="{% url 'users:toggle_activity' pk=object.pk %}">Заблокировать</a>
                {% else %}
                <p class="text-danger">Заблокирован</p>
                <a class="btn btn-outline-success"
                   href="{% url 'users:toggle_activity' pk=object.pk %}">Разблокировать</a>
                {% endif %}
            </div>

            <br>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block title %}Профиль{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card bg-dark text-white">
        <div class="card-header">
          <h3>Профиль</h3>
        </div>
        <div class="card-body">
          <form method="POST" class="form bg-dark text-white">
            {% csrf_token %}
            <div class="text-center mb-4">
              {% if user.avatar %}
              <img src="{{ user.avatar.url }}" alt="Аватар пользователя" width="300" class="img-thumbnail">
              {% endif %}
            </div>
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-secondary">Сохранить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}

{% block title %}Список пользователей{% endblock %}

{% block content %}
<div class="col-12 md-5">
    <h1 class="mt-5">Пользователи</h1>
    <hr>
    <br>
            <table class="table table-striped">
                <tbody>
                {% for object in object_list %}
                {% if not object.is_superuser and not object.is_staff %}
                <tr>
                    <td class="text-white"> {{ object.first_name }} {{ object.last_name }}</td>
                    <td class="text-white">{{ object.email }}</td>
                    <td>
                        <a href="{% url 'users:view' pk=object.pk %}" class="btn btn-outline-secondary">Подробнее</a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}