blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(300)(BlogDetailView.as_view()), name='view'),
]

clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig
from clients.views import ClientCreateView, ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='list'),
    path('view/<int:pk>/', ClientDetailView.as_view(), name='view'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    """Модель для хранения информации о клиентах сервиса"""

    email = models.EmailField(verbose_name='Контактный email')
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    comment = models.TextField(verbose_name='Комментарий', null=True, blank=True)

    # Связь с пользователем
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', default=None)

    def __str__(self):
        return f'{self.full_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        db_table = 'clients'

clients/forms.py
from django import forms

from clients.models import Client


class ClientForm(forms.ModelForm):
    """Форма для работы с клиентом"""

    class Meta:
        model = Client
        fields = ('email', 'full_name', 'comment')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from clients.forms import ClientForm
from clients.models import Client


class UserClientsMixin:
    """Миксин для получения из списка клиентов только клиентов текущего пользователя"""
    def get_queryset(self):
        return Client.objects.filter(user=self.request.user)


class ClientCreateView(LoginRequiredMixin, UserClientsMixin, CreateView):
    """Контроллер для создания нового клиента"""
    model = Client
    form_class = ClientForm

    success_url = reverse_lazy('clients:list')

    def form_valid(self, form):
        user = self.request.user  # Получаем текущего пользователя
        form.instance.user = user  # Привязываем клиента к текущему пользователю
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, UserClientsMixin, ListView):
    """Контроллер для отображения списка клиентов"""
    model = Client


class ClientDetailView(UserClientsMixin, DetailView):
    """Контроллер для отображения информации о клиенте"""
    model = Client


class ClientUpdateView(UserClientsMixin, UpdateView):
    """Контроллер для изменения информации о клиенте"""
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('clients:view', args=[self.kwargs.get('pk')])


class ClientDeleteView(UserClientsMixin, DeleteView):
    """Контроллер для удаления клиента"""
    model = Client
    success_url = reverse_lazy('clients:list')

clients/templates/clients/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block title %}Подтверждение удаления клиента{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mt-4">Подтверждение удаления клиента</h1>
            <hr>
            <br>
            <p>Вы уверены, что хотите удалить клиента "{{ object.full_name }}"?</p>
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Удалить</button>
                <a href="{% url 'clients:list' %}" class="btn btn-outline-secondary">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'main/base.html' %}

{% block title %}Клиент - Mail Flow{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="display-4 mt-5">Подробнее о клиенте</h1>
            <hr>
            <br>


            <dl class="row">
                <dt class="col-sm-3">ФИО:</dt>
                <dd class="col-sm-9" style="margin-bottom: 20px;">{{ object.full_name }}</dd>

                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9" style="margin-bottom: 20px;">{{ object.email }}</dd>

                <dt class="col-sm-3">Комментарий:</dt>
                <dd class="col-sm-9" style="margin-bottom: 20px;">{{ object.comment }}</dd>
            </dl>
           <br>
            <hr>

            <br>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'clients:edit' pk=object.pk %}">Редактировать</a>
                <a class="nav-link" href="{% url 'clients:delete' pk=object.pk %}">Удалить</a>

            </nav>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/client_form.html
{% extends 'main/base.html' %}

{% block title %}{% if form.instance.pk %}Редактирование клиента - {% else %}Создание клиента - {% endif %}Mail Flow{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card bg-dark text-white">
                <div class="card-header">
                    <h3>{% if form.instance.pk %}Редактирование клиента{% else %}Новый клиент{% endif %}</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary mt-3">Сохранить</button>
                        <a href="{% url 'clients:list' %}" class="btn btn-outline-secondary mt-3">Отмена</a>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'main/base.html' %}

{% block title %}Список клиентов - Mail Flow{% endblock %}

{% block content %}
<div class="col-12 md-5">
    <h1 class="mt-5">Клиенты</h1>
    <hr>
    <br>
            <table class="table table-striped">

                <tbody>
                {% for object in object_list %}
                <tr>
                    <td class="light-text">{{ object.full_name }}</td>
                    <td class="light-text">{{ object.email }}</td>
                    <td>
                        <a href="{% url 'clients:view' pk=object.pk %}" class="btn btn-outline-secondary">Подробнее</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <br>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'clients:create' %}">Добавить клиента</a>
            </nav>
        </div>
    </div>
</div>
{% endblock %}