blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', cache_page(300)(BlogDetailView.as_view()), name='view'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, contacts

app_name = MainConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from blog.services import get_cached_articles
from main.services import get_cached_unique_clients, \
    get_cached_mailings, get_active_mailings


from django.shortcuts import render


def home(request):
    """Отображение домашней страницы"""

    # Получаем данные для статистики из кэша
    total_mailings_count = len(get_cached_mailings())
    active_mailings_count = len(get_active_mailings())
    unique_clients_count = len(get_cached_unique_clients())
    articles = get_cached_articles().order_by('?')[:3]

    context = {
        'articles': articles,
        'total_mailings_count': total_mailings_count,
        'active_mailings_count': active_mailings_count,
        'unique_clients_count': unique_clients_count,
        'is_home_page': True,

    }
    return render(request, 'main/home.html', context)


def contacts(request):
    """Отображение страницы с контактами"""

    context = {
        'email': 'example@example.com',
        'phone': '+1 123-456-7890',
        'address': '123 Main Street, City, Country',
        'facebook': 'facebook.com/mailflow',
        'twitter': 'twitter.com/mailflow',
        'instagram': 'instagram.com/mailflow',

    }
    return render(request, 'main/contacts.html', context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Your Name">
    <title>{% block title %}Mail Flow{% endblock %}</title>

    <!-- Подключение Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }

    /* Стиль для светлого текста */
    .light-text {
      color: white; /* Измените цвет текста на светлый */
    }
  }

  /* Ваш остальной CSS-код */
  .mailflow-title {
    margin-top: 1cm;
    margin-left: 1cm;
  }

  body {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
  }

  .mailflow-title-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
    margin-bottom: auto;
  }

  footer {
    text-align: center;
    padding: 1rem;
  }


    </style>

    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">

</head>
<body class="d-flex h-100 text-center text-white bg-dark">


<header class="mb-auto">
    {% if user.is_staff %}
    <div class="alert alert-warning" role="alert">
        Вы зашли как менеджер.
    </div>
    {% endif %}
    <div class="mailflow-title-container">
        <h2 class="mailflow-title">
            <img src="/media/envelope.jpg" alt="logo" class="navbar-logo" width="32" height="32">
            Mail Flow
        </h2>
        {% include 'includes/inc_menu.html' %}
        {% if request.path != '/' %}
        <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link" href="{% url 'main:home' %}">Вернуться на главную</a>
        </nav>
        {% endif %}
    </div>
</header>

<!-- Карточка "Наша статистика" -->
{% if is_home_page %}
<div class="col-md-2 mt-3">
    <div class="card bg-dark mt-3">
        <div class="card-body">
            <h6 class="card-title">Статистика</h6>
            <p class="card-text text-muted">Количество рассылок: {{ total_mailings_count }}</p>
            <p class="card-text text-muted">Активные рассылки: {{ active_mailings_count }}</p>
            <p class="card-text text-muted">Уникальные клиенты: {{ unique_clients_count }}</p>
        </div>
    </div>
</div>
{% endif %}


<main>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
</main>


<footer class="mt-auto text-white-50">
    <p>Mail Flow &copy; 2023 - {% now 'Y' %}</p>
</footer>


<!-- Подключение Bootstrap JS и jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
<div class="container">
    <h1>Контакты</h1>
    <hr>
    <br>
    <h5>Если у вас есть вопросы, предложения или замечания, не стесняйтесь обращаться к нам:</h5>
    <br>
    <br>
    <p>Электронная почта: {{ email }}</p>
    <p>Телефон: {{ phone }}</p>
    <p>Адрес: {{ address }}</p>
    <hr>
    <br>
    <h5>Вы также можете связаться с нами через социальные сети:</h5>
    <br>
    <br>

    <p>Facebook: <a href="#">{{facebook}}</a></p>
    <p>Twitter: <a href="#">{{twitter}}</a></p>
    <p>Instagram: <a href="#">{{instagram}}</a></p>
    <hr>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}Домашняя страница - Mail Flow{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h1 class="display-4 text-center">Добро пожаловать в Mail Flow</h1>
            <p class="lead text-center">Управляйте вашими рассылками с легкостью.</p>
        </div>
    </div>

    <nav class="nav nav-masthead justify-content-center">
        <div class="row">
            {% for article in articles %}
            <div class="col-md-4">
                <div class="card mb-4 bg-dark text-white h-60">
                    <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}"
                         style="width: 100%; height: auto;">
                    <div class="card-body">
                        <h6 class="card-title">{{ article.title }}</h6>
                        <a class="nav-link" href="{% url 'blog:view' pk=article.pk %}">Читать</a>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </nav>
</div>
{% endblock %}